vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
        
    mappings:
        recipe_images:  # Make sure this name is consistent across all usage
            uri_prefix: /images/recipe_images  # URL where files will be accessible
            upload_destination: '%kernel.project_dir%/public/images/recipe_images'  # Local path where files are stored
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer  # Generates a unique filename
